### ISSUE TITLE
[Bug] path should be a `path.relative()`d string, but got ".."

### ISSUE THREAD

**Issue by 2ipm1nd** [huacnlee/autocorrect#100]
Vs code Version

- v2.1.0

it will have errors ``path should be a`path.relative()`d string, but got ".."``,but it will work fine on version 2.0.1

**Comment by huacnlee** [comment]
Please upload a screenshot for this error.

**Comment by 2ipm1nd** [comment]
![vgy.me](https://i.vgy.me/IIPYQo.gif)

**Comment by huacnlee** [comment]
v2.1.1 修复了，等 VS Code Extension 市场更新。
