### ISSUE TITLE
Support markdown list indenttation with 4 spaces

### ISSUE THREAD

**Issue by trdthg** [huacnlee/autocorrect#107]
I was writing some docs with code-server(install manually), but autocorrect doesn't work somehow. I tried to reinstall the extension and use the cmd tool, but finally found that autocorrect doesn't check the nested lists with 4 spaces.

I can use 3 spaces, but would it be better if more choices are supported?

**Comment by huacnlee** [comment]
Would you please give me a markdown text example?

**Comment by trdthg** [comment]
Seems a little different than I thought

![Screenshot 2022-10-26 16 58 45](https://user-images.githubusercontent.com/69898423/197982862-6da45453-9ff2-4e83-af6b-f6277567ca4e.png)

**Comment by huacnlee** [comment]
```
# Demo

- `fn return1`
    
    Hi你好,。

- Hi你好

    Hi你好
```

# Demo

- `fn return1`
    
    Hi你好,。

- Hi你好

    Hi你好

**Comment by trdthg** [comment]
I'm not sure, 

![Screenshot 2022-10-26 17 09 42](https://user-images.githubusercontent.com/69898423/197985290-93b0c8f8-4c4a-4278-a68d-b7eb4f7f40da.png)

```markdown
# Demo

- Hi你好

    Hi你好    

- Hi你好

    - Hi你好
    - Hi你好
```

**Comment by trdthg** [comment]
But if I change indents to 3 spaces, it works.
```markdown
# Demo

- Hi你好

   Hi你好    

- Hi你好

   - Hi你好
    - Hi你好
```

**Comment by huacnlee** [comment]
我知道原因，AutoCorrect 实现的 Markdown Parser，把 4 space ident 认为是 codeblock，codeblock 是不处理的。

这里需要改进识别 list 后面的 4 space indent。
