### ISSUE TITLE
请问是否有禁用「检查并建议」开关或者设置？

### ISSUE THREAD

**Issue by leidichen** [huacnlee/autocorrect#108]
- 写长文本时，满屏黄色波浪线警告，这比中英排版没有空格还要可怕 ~~~~~~~~~ 🫥
- 请问是否有关闭「检查建议」的设置或者开关？在哪里可以取消它
- 我觉得这个插件最棒的地方在于当按下保存时，自动排版，但用户希望使用它时，润物细无声地完成一键排版，而不是在写作过程中不断干扰警告提示😂
- 如有可以关闭这个「检查建议」的设置，那太好了，请尽快告知，谢谢

**Comment by huacnlee** [comment]
我得 VS Code 增加一个开关才行，可以实现的

**Comment by huacnlee** [comment]
好了，2.4.2 版本已经发布了

https://marketplace.visualstudio.com/items?itemName=huacnlee.auto-correct

**Comment by leidichen** [comment]
> 好的，2.4.2版本已经发布了
> 
> https://marketplace.visualstudio.com/items?itemName=huacnlee.auto-correct

![image](https://user-images.githubusercontent.com/18671216/200977785-ad06accc-1357-4f72-82b9-b62c106574af.png)

完美解决！👍🫶

**Comment by gowk** [comment]
"autocorrect.enableLint": false 
设置后为什么还是满屏的黄色波浪线呢？

> 好了，2.4.2 版本已经发布了
> 
> https://marketplace.visualstudio.com/items?itemName=huacnlee.auto-correct

**Comment by huacnlee** [comment]
@gowk 哪里我还需要优化一下，设置关掉以后，已有的诊断（黄色波浪线）没有清理掉，你重新开编辑器就好了。

**Comment by huacnlee** [comment]
@gowk 已经改进了，等 VS Code 插件更新就可以啦

**Comment by leidichen** [comment]
发现一个BUG，当我修改对文档重命名之后，vscode工作区内的其他文档会变成黄色！是不是重命名这个操作会遍历其他文档，我挨个点进去看之后，发现文档内容又是满屏黄色波浪线警告。重启vscode，文档警告消失。
