### ISSUE TITLE
增加对notebook的支持

### ISSUE THREAD

**Issue by yangtzech** [huacnlee/autocorrect#121]
VSCode 插件现在对 VSCode Notebook 中 markdown 不支持，如果可以的话，希望能增加对 Notebook 的支持

**Comment by yangtzech** [comment]
感谢作者的支持，但是使用时好像有bug

```
def test_installation():
    try:
        import filterpy
    except:
        print("请通过运行命令来安装FilterPy：\n\t$ pip install filterpy\n有关说明，请参见《附录A-安装》。")
```
在python .py文件中会有错误提示：
![image](https://user-images.githubusercontent.com/41911522/215257726-28991c8d-18d9-4b37-a409-affc13202eda.png)

但将同样的文字放在.ipynb中就不会有提示
1）放在代码框中；2）放在Markdown中
![image](https://user-images.githubusercontent.com/41911522/215257918-d524fc37-0936-408c-8981-46784a61c20f.png)

**Comment by huacnlee** [comment]
因为 Notebook 目前仅处理了 Markdown 的部分

**Comment by yangtzech** [comment]
> 因为 Notebook 目前仅处理了 Markdown 的部分

即使放置在Markdown的cell中也不会有提示
![image](https://user-images.githubusercontent.com/41911522/215259957-f92687f3-3876-4d32-84db-9073f08af452.png)

**Comment by huacnlee** [comment]
不是。

在 Markdown 里面得是 Markdown 格式才能处理，直接的代码 AutoCorrect 可能会错误识别。你可以看看测试文件：

https://github.com/huacnlee/autocorrect/blob/main/autocorrect/tests/fixtures/jupyter.ipynb


yangtzech ***@***.***>于2023年1月28日 周六下午5:55写道：

**Comment by yangtzech** [comment]
测试文件中好像也不起作用，但将同样的内容复制到Markdown中插件可以起作用

jupyter.ipynb

![image](https://user-images.githubusercontent.com/41911522/215266334-67bf243f-b9a4-4cc4-bbb1-df612c3cd895.png)


jupyter.md
![image](https://user-images.githubusercontent.com/41911522/215266418-fe674b6b-deb1-4cc7-8280-4c4214543498.png)

**Comment by huacnlee** [comment]
应该是 VS Code 这个 Jupyter Notebook 预览模式的问题。

你试试 CLI  里面检查

yangtzech ***@***.***>于2023年1月28日 周六下午8:40写道：

**Comment by yangtzech** [comment]
通过cli检查没问题，多谢
