### ISSUE TITLE
[Markdown] Cannot handle space between punctuation and backtick

### ISSUE THREAD

**Issue by xiaogaozi** [huacnlee/autocorrect#125]
## Case 1

Now (nothing changed):

```diff
-aaa,`code` bbb
+aaa,`code` bbb
```

Expected (add space between punctuation and backtick):

```diff
-aaa,`code` bbb
+aaa, `code` bbb
```

## Case 2

Now (nothing changed):

```diff
-测试测试， `code` 测试测试
+测试测试， `code` 测试测试
```

Expected (delete space between punctuation and backtick):

```diff
-测试测试， `code` 测试测试
+测试测试，`code` 测试测试
```

**Comment by huacnlee** [comment]
这个目前就是这么设计的，没有处理 Markdown `code` 的场景，因为在一些 Markdown 文档里面 `code` 可能已经在 CSS 上给了左右的 margin，AutoCorrect 采取保守做法，不确定有争议的不处理。

这个细节我再想想怎么弄，去多余的空格是应该要做掉。

**Comment by huacnlee** [comment]
```
-aaa,`code` bbb
+aaa, `code` bbb
```

这种暂时为处理，目前 AutoCorrect 对英文都未处理，以免自动纠正的时候破坏了代码。

**Comment by seven1240** [comment]
> 这个目前就是这么设计的，没有处理 Markdown `code` 的场景，因为在一些 Markdown 文档里面 `code` 可能已经在 CSS 上给了左右的 margin，AutoCorrect 采取保守做法，不确定有争议的不处理。
> 
> 这个细节我再想想怎么弄，去多余的空格是应该要做掉。

在HTML场景有办法加样式，但是在PDF场景却不好弄。所以，还是希望能实现 `code` 两侧加空格。

**Comment by seven1240** [comment]
> 这个目前就是这么设计的，没有处理 Markdown `code` 的场景，因为在一些 Markdown 文档里面 `code` 可能已经在 CSS 上给了左右的 margin，AutoCorrect 采取保守做法，不确定有争议的不处理。
> 

可否实现一个选项，如果需要的话开启，处理激进一些，加上两侧空格？

**Comment by huacnlee** [comment]
看新版本已经有了

**Comment by zhuzhidong** [comment]
当前新版本（v2.13.0）好像依然有这个问题

```shell
(0) > cat .\text.txt
测试测试， `code`测试测试
(0) > autocorrect.exe --lint .\text.txt
.
No issues found.
AutoCorrect spend time: 20.36ms
```

配置文件中，反引号的选项已经打开

```yaml
  # Add space between ``, when near the CJK.
  space-backticks: 1
```

期望的行为应该是：

```diff
-测试测试， `code` 测试测试
+测试测试，`code`  测试测试
```
