### ISSUE TITLE
Doesn't work in Markdown code block

### ISSUE THREAD

**Issue by leana8959** [huacnlee/autocorrect#128]
Hello,

Is there a way to activate linting in a Markdown code block globally without adding a comment to activate linting?

Thanks!

**Comment by huacnlee** [comment]
Yes, It's correct.

Because there in codeblock are source code. AutoCorrect lint them by there `lang`, for example:

```js
// lang: js
const hello = "Hello你好"
```

This will use lint by JavaScript.
