### ISSUE TITLE
英文前面有符号时会导致失效

### ISSUE THREAD

**Issue by fenbox** [huacnlee/autocorrect#136]
源内容：

```
你好[]type世界
你好!type世界
```

期望校正后结果：

```
你好 []type 世界
你好 !type 世界
```

**Comment by huacnlee** [comment]
这些场景没处理，是为了避免错误纠正。

AutoCorrect 尽量保守处理 99% 的 case，一些存在争议或自动纠正风险的地方，会选择不处理。

这类基于 AutoCorrect 本身的设计，应该靠手工方式来解决。

**Comment by fenbox** [comment]
@huacnlee 理解
