### ISSUE TITLE
一种未给出修复建议的情况

### ISSUE THREAD

**Issue by Higurashi-kagome** [huacnlee/autocorrect#141]
在 VSCode 中编辑包含如下内容的 Markdown 文件：

```
首先将数组排序（为二分查找做准备），然后对于数组中的每个 a[i]，使用BinarySearch的rank() 方法对-a[i]进行二分查找。如果结果为j且j＞i，我们就将计数器加1。
```

给出的建议如下：

<details>
<summary>演示</summary>

![GIF 2023-1-21 10-40-58](https://user-images.githubusercontent.com/51501079/213840469-28ff00bb-54f8-42b2-bf9c-84e69bf2250c.gif)

</details>

有部分内容未给出中英文修复建议。

**Comment by huacnlee** [comment]
`-a[i]` 这种没处理是保守设计，因为之前发现 `-` 很多场景容易误判，所以就没弄。这类问题目前我的设计想法是靠手功能，避免 autocorrect 错误检查，导致一直提示。

**Comment by huacnlee** [comment]
后面的 `j` 那些我查查是什么原因。
