### ISSUE TITLE
autocorrect 安装问题

### ISSUE THREAD

**Issue by yangtzech** [huacnlee/autocorrect#142]
通过命令安装`curl -sSL https://git.io/JcGER | sh`之后提示`AutoCorrect v2.6.1 has installed successfully.`
但使用`autocorrect -V`会提示未找到命令

![image](https://user-images.githubusercontent.com/41911522/215274486-cbff2bd0-1920-4cfb-a951-448b9f1e1ee5.png)

**Comment by huacnlee** [comment]
什么操作系统？奇怪 /usr/local/bin 目录没有

**Comment by huacnlee** [comment]
手动执行一下 rm -f /usr/local/bin/autocorrect

**Comment by yangtzech** [comment]
找到问题了
sh文件里面缩进的问题

![image](https://user-images.githubusercontent.com/41911522/215303075-77fce697-ca7a-459f-a5b7-cde522692536.png)
把tab改成space就可以了
![image](https://user-images.githubusercontent.com/41911522/215303083-703e6e96-8250-4c02-a464-2020c68e1e9b.png)
安装成功
![image](https://user-images.githubusercontent.com/41911522/215303093-5e291a92-907c-4e11-9e3a-43bd885f9966.png)

**Comment by huacnlee** [comment]
谢谢 我稍后修复一下


yangtzech ***@***.***>于2023年1月29日 周日上午11:45写道：
