### ISSUE TITLE
中文全角的引号

### ISSUE THREAD

**Issue by Luncher** [huacnlee/autocorrect#15]
中文全角的引号前面应该不需要加空格：`“`，目前自动会加一个空格，不支持是不是预期的。譬如：

>你好“世界“

会被格式化成

>你好 “世界”

**Comment by huacnlee** [comment]
等我发布 1.5.5

和 Apple 的网站参考对比了一下，是不应该增加空格。
https://support.apple.com/zh-cn/iphone-12-and-iphone-12-pro-service-program-for-no-sound-issues
