### ISSUE TITLE
在使用过程中遇到了无法正常格式化的情况

### ISSUE THREAD

**Issue by wtklbm** [huacnlee/autocorrect#152]
今天在写笔记的时候，使用 `autocorrect` 遇到了无法格式化的情况：

具体出现问题的字符串为：

`在HTTP/1.1和一部分的HTTP/1.0提出了持久连接的方法(Keep-Alive)。持久连接的特点是，只要任意一端没有明确提出断开连接，则保持TCP连接状态。这样，只需要建立一次TCP连接，就可以进行多次请求-响应的交互。`

预期的效果为：

`在 HTTP/1.1 和一部分的 HTTP/1.0 提出了持久连接的方法 (Keep-Alive)。持久连接的特点是，只要任意一端没有明确提出断开连接，则保持 TCP 连接状态。这样，只需要建立一次 TCP 连接，就可以进行多次请求-响应的交互。`

实际的效果为：
`在HTTP/1.1和一部分的HTTP/1.0提出了持久连接的方法(Keep-Alive)。持久连接的特点是，只要任意一端没有明确提出断开连接，则保持TCP连接状态。这样，只需要建立一次TCP连接，就可以进行多次请求-响应的交互。`

影响该问题的字符串是： `HTTP/1.1` 和 `HTTP/1.0`,将其中的 `/` 替换为空格后，格式化的结果为：

`在 HTTP 1.1 和一部分的 HTTP 1.0 提出了持久连接的方法 (Keep-Alive)。持久连接的特点是，只要任意一端没有明确提出断开连接，则保持 TCP 连接状态。这样，只需要建立一次 TCP 连接，就可以进行多次请求 - 响应的交互。`

**Comment by huacnlee** [comment]
带 `/` 的场景被认为可能是一个 Path 或 URL，所以保守做法没有处理。

**Comment by wtklbm** [comment]
嗯，我看到源代码中确实包含基于正则的 URL 和 PATH 路径的行判断

在格式化文章时，通常文章的字符数通常在一千到几千，甚至有可能上万。如果通过 `autocorrect` 进行格式化，当格式化后，如果其中包含未被格式化的行，且 `autocorrect` 也没有给任何的提示或警告，用户就会自认为每一行都被格式化了。在这种情况下，一方面会影响格式化后文本的呈现效果，另一方面或多或少的影响 `autocorrect` 程序的评价，也会给用户带来疑问: "这里没有被格式化是程序 BUG 还是由什么原因造成的"。在格式化文本后还需要用户从头到尾的检查哪些文本被格式化了，哪些文本没有被格式化，增加了校验和审查的负担。

让 `autocorrect` 来保证所有文本都以正确的方式格式化有困难，但可以让 `autocorrect` 在它不能处理、需要用户手动处理的地方增加提示和警告。

在这方面，我们是否可以考虑增强 `autocorrect` 在处理无法格式化的行的情况，增加一些警告和提示，这样，当用户在格式化文本时，可以借助提示和警告，手动处理那些未被格式化的行。保证每一行文本都是经过处理的。

例如像这样：
![2023-04-07_12 20 43](https://user-images.githubusercontent.com/26459487/230540315-da0e381c-d606-42bd-bcec-90076f22054e.png)

除了增加消息提示之外，还可以增加 `-q` 或 `--quiet` 选项，来抑制这些警告和提示。
或者可以以相反的选项来处理此需求，默认情况下不显示提示和警告，在用户传递 `-v` 时显示更多格式化信息。

**Comment by huacnlee** [comment]
这个问题在 v2.8.5 里面应该修复了。

https://github.com/huacnlee/autocorrect/commit/b93e41f95658fb66969bdb3bfa8c04b8821da21e

```diff
-在HTTP/2与HTTP/1.1里面
+在 HTTP/2 与 HTTP/1.1 里面
```

**Comment by wtklbm** [comment]
这真的是太棒了
