### ISSUE TITLE
[功能请求] 是否可以在 markdown 的格式化中支持反引号

### ISSUE THREAD

**Issue by wtklbm** [huacnlee/autocorrect#153]
一般写 markdown 的时候，常常用到反引号，像这样：

```markdown
- `Type`帧的类型：常用的就是`HEADERS`和`DATA`
- `Flags`标志位：常用的是`END_HEADERS`、`END_STREAM`和`PRIORITY`
```

格式化后，像这样：

```markdown
- `Type` 帧的类型：常用的就是 `HEADERS` 和 `DATA`
- `Flags` 标志位：常用的是 `END_HEADERS`、`END_STREAM` 和 `PRIORITY`
```

是否可以支持 markdown 中这种语法呢？

**Comment by huacnlee** [comment]
因为 ``` `` ``` 里面可能有很多未知的情况，所以 ``` `` ``` 并没有处理。这个我想想

**Comment by wtklbm** [comment]
我发现，在 markdown 中，反引号中是不能包含反引号的，也就是说，即使增加转义 "\\\`" 也是不行的，为此可以通过一个简单的正则来匹配它 "\`[^\`]+\`"，因为我对源代码不清楚，所以也不能确定是否可以通过正则来匹配，或者是其他方式? 只在反引号之外添加适当的空格就可以了，反引号之内的内容应保持不变
