### ISSUE TITLE
[VS Code插件]如何配置.autocorrectrc文件

### ISSUE THREAD

**Issue by 225463** [huacnlee/autocorrect#155]
[插件说明页](https://marketplace.visualstudio.com/items?itemName=huacnlee.autocorrect)提到：可以配置.autocorrectrc文件。
但下载插件后，本地没有找到.autocorrectrc文件，是否另行下载呢？
这个文件放在哪里，可以让VS Code识别到呢？

谢谢！

**Comment by huacnlee** [comment]
手动添加文件，手动编写
