### ISSUE TITLE
NodeJS package: implement JS-based CLI

### ISSUE THREAD

**Issue by queengooborg** [huacnlee/autocorrect#165]
While the Node.js package is helpful, it only seems to provide a JavaScript API, and doesn't provide a CLI.  It would be great to have a CLI available through the Node.js package, so that this project can be properly integrated into the MDN Web Docs' workflow.

**Comment by huacnlee** [comment]
That a good idea, I will think about convert the CLI as a Wasm, then we can use it into Node.js.

**Comment by queengooborg** [comment]
Thank you very much, I'm looking forward to it!

**Comment by huacnlee** [comment]
Hi @queengooborg you can use it now.

https://github.com/huacnlee/autocorrect/releases/tag/v2.7.0

**Comment by queengooborg** [comment]
Thank you so much, @huacnlee!
