### ISSUE TITLE
[feature request]: allow to ignore content between `IGNORE_BLOCK_STRINGS`

### ISSUE THREAD

**Issue by yin1999** [huacnlee/autocorrect#170]
The case is here: https://github.com/mdn/translated-content/blob/29704eeb680dbcbef3f7e91937db493e05964156/files/zh-cn/web/javascript/reference/operators/right_shift/index.md?plain=1#L61-L64

Could we add a feature to ignore to "correct" the content here by wrapping this with `IGNORE_BLOCK_STRINGS` in markdown or HTML. Just like this:

````md
<!-- autocorrect ignore-start -->

```plain
丢弃前: 11100110111110100000000000000110000000000001
丢弃后:             10100000000000000110000000000001
```

<!-- autocorrect ignore-end -->
````

**Comment by huacnlee** [comment]
Use:

````
<!-- autocorrect-disable -->
```
```
<!-- autocorrect-enable -->
````

https://github.com/huacnlee/autocorrect#disable-by-inline-comment

**Comment by yin1999** [comment]
> Use:
> 
> ```
> 
> ```
> ```
> 
> ```
> 
> https://github.com/huacnlee/autocorrect#disable-by-inline-comment

Thanks for the note :)
