### ISSUE TITLE
Toggling autocorrect off not work in LaTeX comments

### ISSUE THREAD

**Issue by myl7** [huacnlee/autocorrect#174]
`% autocorrect: false` can not disable autocorrect as expected in LaTeX comments.

`%( (//|#))? autocorrect(: false|-disable)` are also tried and none of them works.

A [minimal reproducible example] is provided together

[minimal reproducible example]: https://github.com/myl7/autocorrect/tree/mre/latex-toggle

**Comment by huacnlee** [comment]
Try v2.8.5
