### ISSUE TITLE
failed to install by command "cargo install autocorrect"

### ISSUE THREAD

**Issue by sangshuduo** [huacnlee/autocorrect#175]
error: there is nothing to install in `autocorrect v2.8.5`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.

**Comment by huacnlee** [comment]
See https://github.com/huacnlee/autocorrect?tab=readme-ov-file#installation

The autocorrect crate is a lib, not a bin. And I don't like to make it.

**Comment by huacnlee** [comment]
I will try to merge `autocorrect` and `autocorrect-cli`, maybe they are can merge into one by use Rust `feature`.

**Comment by huacnlee** [comment]
I am going to close this, I don't want to merge them.

Because of like this:

https://github.com/longbridgeapp/rust-i18n/pull/66
