### ISSUE TITLE
着重号两边自动加空格

### ISSUE THREAD

**Issue by chenbimo** [huacnlee/autocorrect#177]
请问可以配置着重号两边加空格吗？

**Comment by huacnlee** [comment]
着重号是那个符号，打出来看一下

**Comment by chenbimo** [comment]
你好，是这个 `，键盘的右上角向右亲写的一个小点。

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/releases/tag/v2.9.0
