### ISSUE TITLE
貌似不支持shell脚本

### ISSUE THREAD

**Issue by BrentHuang** [huacnlee/autocorrect#183]
bash脚本文件*.sh，里面的注释文字的autocorrect，貌似没有效果。在rc中加了语言支持：
  # Shell
  shell: shell
  sh: shell

**Comment by BrentHuang** [comment]
也不支持.ipynb，windows10系统上，vscode中。

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/releases/tag/v2.9.1
