### ISSUE TITLE
请求支持 `.qmd` 文件格式

### ISSUE THREAD

**Issue by TomBener** [huacnlee/autocorrect#184]
`.qmd` 是 [Quarto](https://quarto.org/) ([Repo](https://github.com/quarto-dev/quarto-cli)) 的文件扩展名，是基于 Markdown 的一种变体，二者基本上差不多，希望 AutoCorrect 支持处理这种文件格式，非常感谢。

**Comment by huacnlee** [comment]
你可以修改 `.autocorrectrc` 添加 `fileTypes` 将 `qmd` 映射到 markdown 上来支持。

```
fileTypes:
  qmd: markdown
```

**Comment by TomBener** [comment]
好的，非常感谢。
