### ISSUE TITLE
--fix 时的 print 占用太多时间

### ISSUE THREAD

**Issue by cathaysia** [huacnlee/autocorrect#187]
--fix 时会自动打印一行

```
.

AutoCorrect spend time: 21.413ms
```

这个在使用脚本批量格式化文件时会打印过多的 log，并且导致程序运行很慢。

目前 clang-format 等格式化器在格式化成功时不会打印消息。autocorrect 是否也应该考虑这种做法。或者是当 -vv 标志时打开时才打印log。

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/releases/tag/v2.9.1

**Comment by cathaysia** [comment]
现在虽然不会打印 . 了，但是依然会打印：

```
AutoCorrect spend time: 21.139ms

```

一共是两行 log

**Comment by huacnlee** [comment]
这个是需要的，我看过其他的一些工具，他们的结果都有打印

**Comment by cathaysia** [comment]
https://github.com/huacnlee/autocorrect/assets/42114817/427629e6-8b8b-41df-992f-bc10e6ad1c2d

clang-forma 这种看起来并不会打印一条耗时。而且打印耗时感觉很奇怪。

![image](https://github.com/huacnlee/autocorrect/assets/42114817/4516b3e5-bbd8-419e-977c-5e71943fe7aa)

这个地方文件太多就会导致滚屏

**Comment by huacnlee** [comment]
好的，我懂你的场景问题了，我调整一下
