### ISSUE TITLE
对 Markdown 的支持

### ISSUE THREAD

**Issue by Higurashi-kagome** [huacnlee/autocorrect#19]
大多数时候都很好用。感谢维护。

但似乎没有在 VSCode  插件中支持对 Markdown 文件的 Lint？

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/155553405-62d73af6-833d-4819-9cca-6df589b8c205.png)

</details>

另：

尝试在 VSCode 中开启插件：

```
"autocorrect.enable": true,
"autocorrect.formatOnSave": true,
```

然后新建一个 Markdown 文件，在文件中输入 `N~2~为...`，然后保存，会发现转成了 `N~2～为...`（第二个 `~` 变为了一个全角字符），这大概是预期之外的。

暂时禁用 AutoCorrect 并保存：

```
<!-- autocorrect: false -->
N~2~为...
<!-- autocorrect: true -->
```

会发现暂时禁用无效，仍然会被更正。

**Comment by huacnlee** [comment]
跟 Markdown 没关系，AutoCorrect 的全角纠正，本身会处理 `~` 这个场景里面 ~ 在 Markdown 是特殊符号的事情我遗漏了，我会将 ~ 从全角纠正中去掉

**Comment by Higurashi-kagome** [comment]
请问临时禁用无效和 Lint 检查未见波浪线的问题是扩展的原因吗？注意到 VSCode 的问题面板中列出了建议，但编辑器中未见提示（如上）。

**Comment by huacnlee** [comment]
VS Code 插件新版本已经发布了

**Comment by huacnlee** [comment]
那个注释不行，原因是 Markdown 没注释功能。 临时可以用 .autocorrectignore 排除，或 VS Code 的 Save without format 命令来保存

**Comment by Higurashi-kagome** [comment]
> VS Code 插件新版本已经发布了

测试没问题，已不会纠正 ~ 符号。

> 那个注释不行，原因是 Markdown 没注释功能。 临时可以用 .autocorrectignore 排除，或 VS Code 的 Save without format 命令来保存

通常，可在 Markdown 中写 HTML 注释。可考虑支持临时禁用。
