### ISSUE TITLE
[Bug] Lint 跳转失败

### ISSUE THREAD

**Issue by Higurashi-kagome** [huacnlee/autocorrect#20]
AutoCorrect 在 VSCode 的问题面板中给出了纠正建议，但是我点击建议无法正常跳转，提示`无法打开...: Unable to resolve resource...`：

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/155928720-31da0b5a-bc48-4ced-81ec-b5e0ac7d8935.gif)

</details>

**Comment by huacnlee** [comment]
这个应该修复过了，你再试试

**Comment by Higurashi-kagome** [comment]
嗯，可以了。
