### ISSUE TITLE
something not very accurate in .autocorrectrc.default

### ISSUE THREAD

**Issue by BrentHuang** [huacnlee/autocorrect#201]
in the file https://raw.githubusercontent.com/huacnlee/autocorrect/main/autocorrect/.autocorrectrc.default, something not very accurate.

![image](https://github.com/huacnlee/autocorrect/assets/2862064/03238020-7c09-4613-be04-e8ddf1ede581)

**Comment by huacnlee** [comment]
Because we not have `shell` parser. The Ruby and Shell used same `Comment` style, for example: `# `, so it can simply port shell to ruby.


And the C++ is same like that.
