### ISSUE TITLE
[FR] 添加空格的反向操作：移除 CJK 与西文之间的空格

### ISSUE THREAD

**Issue by TomBener** [huacnlee/autocorrect#207]
我平时写 Markdown 会手动在中文和西文之间添加空格，这在 HTML 等格式中是需要的，但转换为 `.docx` 后这个空格是多余的，因为 Microsoft Word 会自动调整空格，手动添加的空格反而会影响间距和断行，所以希望能通过 AutoCorrect 来移除空格。

![CleanShot 2024-05-29 at 11 38 57@2x](https://github.com/huacnlee/autocorrect/assets/49151155/e817aa35-70f0-47a8-9b52-4e31cffa138c)

**Comment by huacnlee** [comment]
去空格是违背设计初衷的，不考虑做这样的事情

**Comment by PeterDaveHello** [comment]
@huacnlee 好奇借題詢問一下，我並不懂日文跟韓文，但詢問了 ChatGPT、Claude、Grok 等 AI 得知日文和韓文並不像中文有在半形英數字元以及全形文字中間插入半形空格區隔的習慣，這部份想請問是有考慮讓他們可以分開被設定或區隔差異的嗎？謝謝
