### ISSUE TITLE
HTML <script> Content Should Not Be Modified

### ISSUE THREAD

**Issue by liaohch3** [huacnlee/autocorrect#230]
Description:

When using the autocorrect library to format HTML content, I found that the content inside <script> tags is being incorrectly modified. The expected behavior is that the library should preserve script content as-is since altering it could break JavaScript functionality.

Here’s a minimal reproducible example:

Steps to Reproduce:
	1.	Use the following code to test:
```python
import autocorrect_py as autocorrect

# Test script content to ensure it remains unchanged
html = """<div>
<script>
var test = "这是test脚本";
console.log("Hello世界"); 
</script>
<p>这是test段落</p>
</div>"""

got = autocorrect.format_for(html, 'html')
print("Formatted Result:")
print(got)

# Expected script content to remain unchanged
want = """<div>
<script>
var test = "这是test脚本";
console.log("Hello世界"); 
</script>
<p>这是 test 段落</p>
</div>"""

print("\nDoes the result match expectations:")
print(got.strip() == want.strip())
```

Actual Output:
```python
Formatted Result:
<div>
<script>
var test = "这是 test 脚本";
console.log("Hello 世界"); 
</script>
<p>这是 test 段落</p>
</div>

Does the result match expectations:
False
```

Expected Output:

The content within <script> tags should remain untouched. The expected output is:
```python
<div>
<script>
var test = "这是test脚本";
console.log("Hello世界"); 
</script>
<p>这是 test 段落</p>
</div>
```
Impact:

Modifying <script> content can break JavaScript logic, making this behavior unsuitable for processing HTML documents with embedded scripts.

Suggested Solution:

The library should ignore any text within <script> (and potentially <style>) tags when formatting HTML content.

Thank you for your time and consideration! Let me know if I can provide additional details.

**Comment by huacnlee** [comment]
This is a feature, not a bug. All in string should be correct.

**Comment by liaohch3** [comment]
Thank you for your response and for explaining the autocorrect-disable and autocorrect-enable features.

However, I’d like to clarify my use case:
	1.	Use Case:
I am using this library to process outputs generated by an AI model (Claude). Since these outputs are dynamically generated, I cannot manually insert comments like // autocorrect-disable or // autocorrect-enable into the AI-generated text. This makes it difficult to leverage the disable/enable functionality for script content.

	2.	Inconsistent Behavior Across Versions:
I am using the Python version of this library. I noticed that the behavior of the Golang version is different in handling <script> tags. Specifically, in this [test case](https://github.com/longbridge/autocorrect/blob/main/html_test.go#L37C1-L46C1), the content inside <script> is left unchanged, which aligns better with my expectations:

func TestFormatHTMLWithSameTextInAttribute(t *testing.T) {
    html := `<p data-value="每股均价9.582港元，增持270.3万股"><script>var value = "三生制药获JP Morgan以";</script><pre>每股均价9.582港元</pre><textarea>文本框test</textarea><style>//增持270.3万股</style>三生制药获JP Morgan以<i>每股均价9.582港元，增持270.3万股</i>增持</p>`
    expected := `<p data-value="每股均价9.582港元，增持270.3万股"><script>var value = "三生制药获JP Morgan以";</script><pre>每股均价9.582港元</pre><textarea>文本框test</textarea><style>//增持270.3万股</style>三生制药获 JP Morgan 以<i>每股均价 9.582 港元，增持 270.3 万股</i>增持</p>`
    out, err := FormatHTML(html)
    if err != nil {
        t.Error(err)
    }
    assert.EqualHTML(t, expected, out)
}

Here, the <script> tag content is untouched, while other parts of the HTML are corrected, which makes it safer and more predictable for use with dynamic HTML documents.

Would it be possible to make the Python version consistent with the Golang implementation? Or could we introduce an option to skip processing content inside <script> and <style> tags? This would make the library more flexible for use cases like mine.

Thank you again for your time and for maintaining this great library!

**Comment by cesaryuan** [comment]
> Thank you for your response and for explaining the autocorrect-disable and autocorrect-enable features.
> 
> However, I’d like to clarify my use case:
> 
> Use Case: I am using this library to process outputs generated by an AI model (Claude). Since these outputs are dynamically generated, I cannot manually insert comments like // autocorrect-disable or // autocorrect-enable into the AI-generated text. This makes it difficult to leverage the disable/enable functionality for script content.
> 
> Inconsistent Behavior Across Versions: I am using the Python version of this library. I noticed that the behavior of the Golang version is different in handling <script> tags. Specifically, in this [test case](https://github.com/longbridge/autocorrect/blob/main/html_test.go#L37C1-L46C1), the content inside <script> is left unchanged, which aligns better with my expectations:
> 
> ```python
> func TestFormatHTMLWithSameTextInAttribute(t *testing.T) {
>     html := `<p data-value="每股均价9.582港元，增持270.3万股"><script>var value = "三生制药获JP Morgan以";</script><pre>每股均价9.582港元</pre><textarea>文本框test</textarea><style>//增持270.3万股</style>三生制药获JP Morgan以<i>每股均价9.582港元，增持270.3万股</i>增持</p>`
>     expected := `<p data-value="每股均价9.582港元，增持270.3万股"><script>var value = "三生制药获JP Morgan以";</script><pre>每股均价9.582港元</pre><textarea>文本框test</textarea><style>//增持270.3万股</style>三生制药获 JP Morgan 以<i>每股均价 9.582 港元，增持 270.3 万股</i>增持</p>`
>     out, err := FormatHTML(html)
>     if err != nil {
>         t.Error(err)
>     }
>     assert.EqualHTML(t, expected, out)
> }
> ```
> 
> Here, the <script> tag content is untouched, while other parts of the HTML are corrected, which makes it safer and more predictable for use with dynamic HTML documents.
> 
> Would it be possible to make the Python version consistent with the Golang implementation? Or could we introduce an option to skip processing content inside <script> and <style> tags? This would make the library more flexible for use cases like mine.
> 
> Thank you again for your time and for maintaining this great library!

Maybe you should open a new issue to let author notice it

**Comment by SunayQurbanova** [comment]
Bunu nasıl düzelte bilirim

5 Oca 2025 Pzr 05:08 tarihinde Cesaryuan ***@***.***> şunu
yazdı:
