### ISSUE TITLE
请问 自动将半角符号改为全角符号 这个功能可以配置吗?

### ISSUE THREAD

**Issue by HenryTSZ** [huacnlee/autocorrect#24]
如题, 习惯汉字用半角符号了

只想要 补充正确的空格 这个功能

**Comment by huacnlee** [comment]
你的期望与 AutoCorrect 要解决和愿景方向是相悖的。

我实现这个工具的目的是想要一劳永逸的解决（标准化）文案书写的各类笔误问题。以便与各类文案，例如撰写书籍、文档、项目源代码等等可以借此轻松实现标准化、专业化的文案输出。
