### ISSUE TITLE
[BUG] 带有 `-【】` 中间空格会自动去掉

### ISSUE THREAD

**Issue by forecho** [huacnlee/autocorrect#44]
理论上 `-【】` 中间的空格应该保留。

去掉空格示例：

-【新增】
-【新增】

保留空格示例：

- 【新增】
- 【新增】

**Comment by j1g5awi** [comment]
https://github.com/huacnlee/autocorrect/blob/4cbf2a4bfc8cde64c6150cf07bd28a6e8af0b898/autocorrect/grammar/markdown.pest#L18

临时解决方法：`heading_tag = @{"######" | "#####" | "####" | "###" | "##" | "#" | "-"}`

**Comment by huacnlee** [comment]
去掉空格是合理的。中文的括号本身有视觉间距，再加就间隔过多了。

**Comment by j1g5awi** [comment]
这与 markdown 语法不兼容，在 markdown 列表中应当禁用此规则。

以及有些 markdown 有 [front matter](https://gohugo.io/content-management/front-matter/)，需要将该部分当作另一格式来 lint，否则也会出现删除空格导致语法错误的问题。

**Comment by huacnlee** [comment]
I see, 我会试着修复一下

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/releases/tag/v1.9.2

**Comment by Dunky-Z** [comment]
@huacnlee Jason你好

```bash
$ autocorrect --version
AutoCorrect 1.10.5
```
Windows平台，1.10.5版本，依然会将Markdown文件的front matter，的`---`符号自动删除。

**Comment by huacnlee** [comment]
更新版本
