### ISSUE TITLE
希望vscode-extensions能同步一份到open-vsx

### ISSUE THREAD

**Issue by zWingz** [huacnlee/autocorrect#55]
https://open-vsx.org/
vscode自身的插件市场只能用在vscode产品上, 因此衍生出了open-vsx, 允许上面的插件用于其他产品, 因此希望autoCorrect也同步一份到open-vsx上

**Comment by huacnlee** [comment]
抱歉，没时间维护其他平台。

**Comment by Vinfall** [comment]
How about now?

Open VSX is used by most derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io/), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

[Publishing an extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) is straightforward and shouldn't take long. You can also automate the whole process with [GitHub Action integration](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md).
