### ISSUE TITLE
請問一下 windows 桌面版如何使用？

### ISSUE THREAD

**Issue by 2ipm1nd** [huacnlee/autocorrect#56]
抱歉我下載 windows 桌面版的壓縮檔，裡面就只有一個 exe 檔，我點擊之後完全沒反應，請問我應該怎麼做呢？

**Comment by huacnlee** [comment]
CMD 里面执行

如果还是不会，可以试试 VS Code 插件

https://marketplace.visualstudio.com/items?itemName=huacnlee.auto-correct

**Comment by 2ipm1nd** [comment]
瞭解，已經知道如何使用。最後還是轉到vscode，方便許多，感謝您。
