### ISSUE TITLE
不支持 C++？

### ISSUE THREAD

**Issue by ZJUGuoShuai** [huacnlee/autocorrect#62]
目前似乎不支持检查 C++ 源文件？

示例文件：`hello.cc`
```cpp
// 你好world
```
运行 `autocorrect`：
```shell
$ ./autocorrect hello.cc
无输出
```

把 `.cc` 重命名成 `.txt`：
```shell
$ mv hello.cc hello.txt
$ ./autocorrect hello.txt
// 你好 world
```

**Comment by huacnlee** [comment]
对，目前还不支持

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/tree/v1.10.0

**Comment by ZJUGuoShuai** [comment]
@huacnlee 匹配的后缀名是否可以考虑可以加上 `.h`、`.cu` 和 `.cuh`？即 C/C++ 头文件、CUDA 源文件以及 CUDA 头文件，都使用同一套语法规则（CUDA 定义了一些额外的语法，但不影响字符串和注释）。
