### ISSUE TITLE
[JS] 运行wasm报错

### ISSUE THREAD

**Issue by Maicarons2022** [huacnlee/autocorrect#63]
node_modules/@huacnlee/autocorrect/autocorrect_bg.js 的170行`wasm.__wbindgen_add_to_stack_pointer(16);`在Chrome中报错并无法运行:
```
Uncaught (in promise) TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function
```

实现代码
```jsx

    let [value, setValue] = React.useState(`# Hello你好!`);
    let Out1;
    autocorrect.then((autocorrect) => {
        Out1 = autocorrect.format(value); //报错 
    });
```

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/blob/main/example/index.js

参考

**Comment by JounQin** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/8336744/188469195-39fe9d3c-1816-41eb-b4d3-9349e842af7d.png">

@huacnlee 包定义有问题，应该是 `"type": "module"` + `"main": "autocorrect.js"`

**Comment by JounQin** [comment]
另外，`.wasm` 不能直接在 `.js` 里 import 使用，现在在 node 端一直报错 `"Invalid or unexpected token"`

https://github.com/un-ts/prettier/blob/feat/autocorrect/packages/autocorrect/test/__snapshots__/fixtures.spec.ts.snap

**Comment by huacnlee** [comment]
我正在重新打包，单独打了一个 @huacnlee/autocorrect-node 为 Node.js 支持。

https://github.com/huacnlee/autocorrect/runs/8198937731?check_suite_focus=true

**Comment by JounQin** [comment]
@huacnlee 打包失败了

**Comment by huacnlee** [comment]
好了，可以安装了，CI 我慢慢解决

**Comment by JounQin** [comment]
@huacnlee 可以考虑用原生不打包的方式加载 .wasm ？https://developer.mozilla.org/zh-CN/docs/WebAssembly/Loading_and_running

这样 browser 和 node 不用分包，也可以原生加载。

**Comment by huacnlee** [comment]
我这个是靠 [wasm-pack ](https://github.com/rustwasm/wasm-pack) 打包的，昨天看了一下，似乎不支持这样做。

**Comment by JounQin** [comment]
> 我这个是靠 [wasm-pack ](https://github.com/rustwasm/wasm-pack) 打包的，昨天看了一下，似乎不支持这样做。

好吧，我想想有没有别的办法解决这个问题，现在等于说 `@huacnlee/autocorrect` 这个包必须要求由 `webpack` 之类的 bundler 来打包了。

**Comment by huacnlee** [comment]
@JounQin Node.js 可以用新的 FFI 方式打包出来的，效率更高一些。

https://github.com/huacnlee/autocorrect/tree/main/autocorrect-node
