### ISSUE TITLE
What does `loadConfig` do? Can I have different and nested `.autocorrectrc` files?

### ISSUE THREAD

**Issue by JounQin** [huacnlee/autocorrect#67]
As title.

And can `formatHTML` or `formartFor` parse the `loadedConfig` manually? So that it will be no possible to conflict with nested files.

**Comment by huacnlee** [comment]
AutoCorrect 目前是单例模式运行的，所以不能同时有多个不同的配置分开加载。

要做到这个，需要重构掉才行。

**Comment by huacnlee** [comment]
https://github.com/huacnlee/vscode-auto-correct/blob/04da138a88801f030e7876a5f3ffeb69c621f5a3/src/util.ts#L21

**Comment by JounQin** [comment]
@huacnlee `autocorrect-cli` 本身还是还是不支持多个 `. autocorrectrc` 是么？

**Comment by huacnlee** [comment]
对 不支持
