### ISSUE TITLE
spellcheck: replacement in codeblock without '```'

### ISSUE THREAD

**Issue by lzufalcon** [huacnlee/autocorrect#68]
Hello, Markdown do support such codeblock style (for example, use 4 whitespaces after a line without indent)

```
Test for words replacement in codeblock like this:

    // this is a 'echo' command line demo to print a string: linux
    $ echo linux

    // another demo
    $ cmd-linux -g linux
```

But the word 'linux' will be replaced by 'Linux' after running autocorrect.

```
Test for words replacement in codeblock like this:

    // this is a 'echo' command line demo to print a string: linux
    $ echo Linux

    // another demo
    $ cmd-linux -g Linux
```

If wrap the above codeblock with '```', it is ok.

may be two solve directions:

1. line with '$' or '#' are command lines (but sometimes, users not explictly add '$' or '#' prompt), which should not be touched, otherwise, the command demo instructions will differ from the original requirement
2. detect such codeblock style and let them work like the codeblock wrapped with '```'

**Comment by Edit-Mr** [comment]
想請教一下我使用的時候還是一直會遇到 Markdown 檔案裡面的 Code Block 被糾錯的問題，想請教一下是我設定的問題嗎？

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/709c4456-c9fe-4b79-9a47-5520b0ee41fb" />

是直接使用 readme 範例的 config 改成 `spellcheck: 1`，然後使用 `yarn autocorrect --fix`。

**Comment by huacnlee** [comment]
Spellcheck 实现还有不少问题，你可以关掉它
