### ISSUE TITLE
VSCode是否可以配置.autocorrectrc？

### ISSUE THREAD

**Issue by Dunky-Z** [huacnlee/autocorrect#69]
插件介绍里说明提到有**支持 .autocorrectrc 配置文件**。但是没有说明配置方法，目前根据example添加了.autocorrectrc 配置文件放在待格式化文档同级目录，并不生效。请问VSCode如何配置 .autocorrectrc ？谢谢！

**Comment by huacnlee** [comment]
VS Code 是读取的项目根目录的，配置是跟着项目走。
