### ISSUE TITLE
超长文本(20W字符)执行失败

### ISSUE THREAD

**Issue by Dunky-Z** [huacnlee/autocorrect#70]
您好，感谢分享，短文章很好用，效率和准确度都很高。但是在Correct长文章时，出现了问题。

20W的字符，I5 10代 用了8线程，运行了大概24小时仍然没有结束。

- 是否有字符上限？
- 建议字符是多少？

谢谢！

**Comment by huacnlee** [comment]
文件能上传吗？文件有多大？

**Comment by Dunky-Z** [comment]
不方便上传呢，20万个字符，280Kb左右。

**Comment by Dunky-Z** [comment]
谢谢修复！CLI可以correct成功。
顺便问一下VSCode会同步更新吗？VSCode插件有一个问题，开启后经常会导致回车键与退格键失效。这个不太好复现，没有日志，也不会弹出警告窗口。每次我都得Disable插件，重新打开窗口才能恢复。不知是否有人反馈相同问题。感谢回复！
