### ISSUE TITLE
Bug: whitespace wrongly added between chinese and "-number" 

### ISSUE THREAD

**Issue by lzufalcon** [huacnlee/autocorrect#87]
orig:

```
* [参考900-资料一][001]
* [参考-900资料二][002]
```

corrected:

```
* [参考 900-资料一][001]
* [参考 -900 资料二][002]
```

The first one is ok, the 2nd one is wrong, it should be: `* [参考-900 资料二][002]`.

Note: in normal content, there is no such issue.

**Comment by huacnlee** [comment]
`-900`  is for the number case.

```
值为 -2 度
···

So, you can use `<!-- autocorrect-disable -->` for disable this line.

**Comment by huacnlee** [comment]
Now use version 2.2.0, you can use `textRules` for ignore those caes.
