### ISSUE TITLE
官方语言调试器报错

### ISSUE THREAD

**Issue by xiayulu** [huacnlee/autocorrect#9]
大佬你好，我最近打算用 Rust pest 写一个 markdown 解析器。不过我用这个[官方语法调试器](https://pest.rs/#editor)调试报错怎么办呢？

![image](https://user-images.githubusercontent.com/41274826/133579370-e26573ab-e279-4776-95fe-2d1a81d7b45b.png)

Rust 小菜鸟求带 :sob:

**Comment by huacnlee** [comment]
PEG 模式，是需要实现所有场景，对每一种变数都覆盖到，有一个漏掉的都不行

**Comment by huacnlee** [comment]
所以你看 autocorrect 里面，我有个 OTHER 类型，用于覆盖那些我没支持的，然后转换的时候保持原始输出

**Comment by huacnlee** [comment]
https://github.com/huacnlee/autocorrect/blob/main/src/lib/grammar/markdown.pest  这个不能用于参考，autocorrect 的场景是为了修正 “字符串” 里面的格式，所以这个 `markdown.pest` 文件优先是找出了不想处理的部分，忽略掉了。

而其他的 pest 文件，例如 `ruby.pest` 和  Markdown 的处理相反，是找出 string, comment 等需要处理的，把其他未识别的当成 `other` 不做处理。
