### ISSUE TITLE
[bug] release 中提供的 windows 平台压缩包格式有误

### ISSUE THREAD

**Issue by batkiz** [huacnlee/autocorrect#90]
```shell
> sha256sum autocorrect-windows-amd64.tar.gz
83af18ccee6e78564b4760a0aa0256b6918dcf681a8f1194f7b69ce6d2e76b7a  autocorrect-windows-amd64.tar.gz

> gunzip -c autocorrect-windows-amd64.tar.gz > autocorrect-windows-amd64.tar    

> ls
autocorrect-windows-amd64.tar  autocorrect-windows-amd64.tar.gz

> file autocorrect-windows-amd64.tar
autocorrect-windows-amd64.tar: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

> tar -xzf autocorrect-windows-amd64.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

` autocorrect-windows-amd64.tar.gz` 应是 autocorrect.exe 先使用 tar 归档，再使用 gzip 压缩生成的文件；但看起来似乎是直接对 autocorrect.exe 进行 gzip 压缩。

**Comment by batkiz** [comment]
https://github.com/huacnlee/autocorrect/blob/d8988a3a0fce5ea05b45af44e1e77bdcd565f64d/.github/workflows/release.yml#L87

这里只对 autocorrect.exe 进行了 `7z a`

https://github.com/huacnlee/autocorrect/blob/d8988a3a0fce5ea05b45af44e1e77bdcd565f64d/.github/workflows/release.yml#L39

但这里将压缩包命名为了 `autocorrect-windows-amd64.tar.gz`

**Comment by huacnlee** [comment]
谢谢
